# Generated by Django 3.0.5 on 2020-04-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200429_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='tag',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
