# Generated by Django 3.0.5 on 2020-04-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200429_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
    ]
