# Generated by Django 3.0.5 on 2020-04-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_remove_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(null=True, upload_to='Tractor Show'),
        ),
    ]
