# Generated by Django 3.0.5 on 2020-06-10 23:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
